name: Deploiement OVH SFTP

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Cloner le dépôt
              uses: actions/checkout@v3

            - name: Installer Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Installer les dépendances
              run: npm ci
              working-directory: ./maVitrine

            - name: Build des assets
              run: npm run build
              working-directory: ./maVitrine

            - name: Déployer via SFTP
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.SFTP_HOST }}
                  username: ${{ secrets.SFTP_USERNAME }}
                  password: ${{ secrets.SFTP_PASSWORD }}
                  port: ${{ secrets.SFTP_PORT }}
                  source: "maVitrine/public/build/*"
                  target: ${{ secrets.SFTP_TARGET }}
