name: Deploiement OVH SFTP

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout du dépôt
              uses: actions/checkout@v3

            - name: Installer les dépendances Node.js
              run: npm ci
              working-directory: ./

            - name: Build des assets
              run: npm run build
              working-directory: ./

            - name: Déployer via SCP
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SFTPHOST }}
                  username: ${{ secrets.SFTPUSER }}
                  password: ${{ secrets.SFTPPASSWORD }}
                  port: ${{ secrets.SFTPPORT }}
                  source: "public/build/*"
                  target: "/home/bellees/maVitrine/public/build"
